apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  restartPolicy: Always

  volumes:
    - name: license-volume
      secret:
        secretName: license-secret

    - name: notebooks
      hostPath:
        path: /home/z2h/dev/mini-data-platform-dev/notebooks
        type: DirectoryOrCreate

  initContainers:
    - name: license-check
      image: z2hx/z2h-license-check:2.0
      volumeMounts:
        - name: license-volume
          mountPath: /licenses
          readOnly: true

  containers:
    - name: jupyter
      image: 3xploiterx/jupyter-base:latest

      # ahora JUPYTER_PASSWORD viene del Secret y se expande igual
      command: ["sh", "-c", "start-notebook.sh --NotebookApp.token=${JUPYTER_PASSWORD}"]

      envFrom:
        - configMapRef:
            name: jupyter-config
        - secretRef:
            name: jupyter-secret

      securityContext:
        runAsUser: 0
        runAsGroup: 0

      volumeMounts:
        - name: license-volume
          mountPath: /licenses
          readOnly: true
        - name: notebooks
          mountPath: /home/jovyan/work
